name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      project:
            description: 'Select project'
            required: true
            default: desktop
            type: choice
            options:
              - create-item
              - edit-item
              - delete-existing-item
              - check-item
              - desktop
              - mobile
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Project: ${{ github.event.inputs.project }}"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Job ID: $GITHUB_RUN_NUMBER"
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ github.event.inputs.project }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium 

    - name: Run Playwright tests
      run: npx playwright test --project=${{ env.PROJECT }}
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
