export function randomWords(length: number) {
    const words = [
      "stranger",
      "things",
      "eleven",
      "hawkins",
      "demogorgon",
      "upside",
      "down",
      "mike",
      "will",
      "dustin",
      "lucas",
      "joyce",
      "hopper",
      "mindflayer",
      "eggo",
      "lab",
      "monster",
      "bike",
      "school",
      "friends",
      "power",
      "mystery",
      "secret",
      "danger",
      "escape",
      "adventure",
      "science",
      "fiction",
      "series",
      "netflix",
      "creepy",
      "shadow",
      "gate",
      "flashlight",
      "walkie",
      "talkie",
      "arcade",
      "snowball",
      "mall",
      "fireworks",
      "summer",
      "night",
      "fear",
      "brave",
      "team",
      "rescue",
      "investigate",
      "weird",
      "creature",
      "experiment",
      "portal",
    ];
    let result = "";
    while (result.length < length) {
      result += words[Math.floor(Math.random() * words.length)] + " ";
    }
    return result.substring(0, length);
  }